services:
  - type: web
    name: visage
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements-railway.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --worker-class sync
    envVars:
      - key: PORT
        value: 5000

